I believe I wrote the correct code, based on experiments in the noteb…
ciemss/pyciemss pull request #201
Opened 2023-07-04 01:55 UTC by djinnome

…ook. Will test next.

2023-07-06 02:41 UTC, SamWitty commented
@djinnome , this is tagged as `awaiting review` but there are some failing tests. Is this actually still a WIP?

2023-07-06 04:00 UTC, djinnome commented
Hi @SamWitty tests now pass, but I am still blocked on https://github.com/indralab/mira/issues/189
If the AMR `id` is different from the `name`, then there is no easy way to associate the rate law symbols with the appropriate concept.

2023-07-06 13:28 UTC, SamWitty commented
Thanks for the update @djinnome . Could you revise the name of this PR to something more informative?

2023-07-07 12:55 UTC, SamWitty requested changes
This looks good overall. Could you rerun the integration demos with these changes? This should produce output files without any `mira_param` parameters, and with the solution variable names according to the id, not the long name. Please check this and then I'll approve.

2023-07-07 12:56 UTC, SamWitty commented on src/pyciemss/PetriNetODE/base.py
> +        setattr(self, "deriv", self.compile_deriv_function())
@djinnome could you also address this minor nit?

2023-07-07 12:56 UTC, SamWitty commented on src/pyciemss/PetriNetODE/base.py
> +            states = {v: state[i] for i, v in enumerate(self.var_order.keys())}
@djinnome ping?

2023-07-07 22:01 UTC, djinnome commented on src/pyciemss/PetriNetODE/base.py
> +        setattr(self, "deriv", self.compile_deriv_function())
Line 304 handles this:

```python
if self.compile_rate_law_p:
   self.compiled_rate_law = self.compile_rate_law()
```

2023-07-07 22:06 UTC, djinnome commented on src/pyciemss/PetriNetODE/base.py
> +            states = {v: state[i] for i, v in enumerate(self.var_order.keys())}
`var_order` is created in the `super().__init__()` constructor, but `states` is determined at the time that `deriv` is called, so I can't move this line out of the `deriv` method

2023-07-07 23:28 UTC, djinnome commented
I have rerun the `integration_demo` notebook and it now generates output without `aggregate_parameters` by default.

2023-07-10 09:20 UTC, SamWitty approved these changes
Looks great!

2023-07-10 09:20 UTC, merged