Adding support for ensemble output format
ciemss/pyciemss pull request #570
Opened 2024-04-11 20:29 UTC by anirban-chaudhuri

2024-04-12 01:35 UTC, sabinala approved these changes
Nice!

2024-04-12 01:38 UTC, sabinala commented
Why are all of the checks failing...oh no! We should fix that before merging.

2024-04-12 01:39 UTC, sabinala commented
Especially the linting? When I enter `make format` it says all of the files are fine.

2024-04-12 13:50 UTC, SamWitty commented
> Especially the linting? When I enter `make format` it says all of the files are fine.

@sabinala , `make format` does not automatically resolve typing inconsistencies, which is a good thing. Use `make lint` locally to see if the linter would pass.

2024-04-16 19:28 UTC, SamWitty commented
@anirban-chaudhuri , I believe I resolved the current issues causing failing test in #572 . I created a separate PR because that contribution was independent of this one, although it is blocking.

2024-04-18 20:08 UTC, SamWitty requested changes
This looks good overall. I've included some specific comments throughout.

My main general comment is that this specialized output processing should not be applied inside of the PyCIEMSS `sample` interfaces, as generating the samples and processing them are really separate computations. Instead let's just leave the new processing utilities as standalone functions, and apply them to the output of `sample` only when necessary.

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/integration_utils/result_processing.py
> +        # timepoints = [*timepoints]
Please remove this commented out line

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/integration_utils/result_processing.py
> +        result_q = make_quantiles(
Could you rename `result_q` to something a bit more informative?

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/integration_utils/result_processing.py
> +                # if "cum" in k.lower():
Please remove commented out code

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/integration_utils/result_processing.py
> +                # if "cum" in k.lower():
Please remove commented out code

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/integration_utils/result_processing.py
> +                    # "inc_cum",
please remove commented out code

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/interfaces.py
> +    alpha_qs: Optional[List[float]] = [
See previous comment about `DEFAULT_ALPHA_QS`.

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/interfaces.py
>          return prepare_interchange_dictionary(
I would strongly prefer for us to not include this very specific output processing in the definition of `sample`. Instead, let's have the ensemble_quantiles be generated separately if needed from the existing output of `sample`.

2024-04-18 20:08 UTC, SamWitty commented on pyciemss/interfaces.py
>          return prepare_interchange_dictionary(
This way we can mix and match output formats if they change in the future.

2024-04-19 14:53 UTC, anirban-chaudhuri commented on pyciemss/integration_utils/result_processing.py
> +    alpha_qs: Optional[List[float]] = [
done

2024-04-22 12:56 UTC, SamWitty requested changes
One minor change requested.

2024-04-22 12:56 UTC, SamWitty commented on pyciemss/interfaces.py
> +DEFAULT_ALPHA_QS = [
Could you import this from `pyciemss.integration_utils.result_processing` instead of redefining it here?

2024-04-25 15:29 UTC, SamWitty approved these changes

2024-04-25 16:32 UTC, merged